In [3]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [4]:
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#concatenate for columns
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
#concatenate row
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#concatenating in pandas

#Series 
ser1=Series([0,1,2],index=["T","U","V"])
ser2=Series([3,4],index=["X","Y"])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [11]:
#concatenating series
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
#concatenating for column
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [14]:
pd.concat([ser1,ser2],keys=["cat1","cat2"])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [17]:
dframe1=DataFrame(np.random.randn(4,3),columns=["X","Y","Z"])
dframe2=DataFrame(np.random.randn(3,3),columns=["Y","Q","X"])

In [18]:
dframe1

X         Y         Z
0  0.055684  1.193452  1.004267
1 -1.403996  1.041092 -0.266474
2  0.835887 -0.411256  0.633153
3  1.457214 -1.558125 -0.326480

In [19]:
dframe2

Y         Q         X
0 -0.902367 -0.115109 -0.291568
1  0.912361  0.360871 -0.538530
2  2.188910  1.938171  0.775852

In [20]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.055684  1.193452  1.004267
1       NaN -1.403996  1.041092 -0.266474
2       NaN  0.835887 -0.411256  0.633153
3       NaN  1.457214 -1.558125 -0.326480
0 -0.115109 -0.291568 -0.902367       NaN
1  0.360871 -0.538530  0.912361       NaN
2  1.938171  0.775852  2.188910       NaN

In [22]:
pd.concat([dframe1,dframe2],axis=1)

X         Y         Z         Y         Q         X
0  0.055684  1.193452  1.004267 -0.902367 -0.115109 -0.291568
1 -1.403996  1.041092 -0.266474  0.912361  0.360871 -0.538530
2  0.835887 -0.411256  0.633153  2.188910  1.938171  0.775852
3  1.457214 -1.558125 -0.326480       NaN       NaN       NaN

In [23]:
#ignore index
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.055684  1.193452  1.004267
1       NaN -1.403996  1.041092 -0.266474
2       NaN  0.835887 -0.411256  0.633153
3       NaN  1.457214 -1.558125 -0.326480
4 -0.115109 -0.291568 -0.902367       NaN
5  0.360871 -0.538530  0.912361       NaN
6  1.938171  0.775852  2.188910       NaN